[versions]
fabric_loom = "1.14-SNAPSHOT"
modpublish = "1.1.0"

minecraft = "1.21.11"
parchment = "2025.10.12"

fabric_loader = "0.18.1"
fabric_api = "0.140.2+1.21.11"

spectre = "0.0.25+1.21.11"

biolith = "3.5.0-beta.2"

modmenu = "17.0.0-alpha.1"

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
modpublish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "modpublish" }

[libraries]
minecraft = { group = "mojang", name = "minecraft", version.ref = "minecraft" }
parchment = { group = "org.parchmentmc.data", name = "parchment-1.21.10", version.ref = "parchment" }

fabric_loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric_loader" }
fabric_api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric_api" }

spectre = { group = "dev.spiritstudios", name = "spectre", version.ref = "spectre" }

biolith = { group = "com.terraformersmc", name = "biolith-fabric", version.ref = "biolith" }
modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu" }
