[versions]
fabric_loom = "1.11-SNAPSHOT"
minotaur = "2.+"

minecraft = "1.21.8"
parchment = "2025.09.14"

fabric_loader = "0.17.2"
fabric_api = "0.134.0+1.21.8"

specter = "1.3.0"

geckolib = "5.2.2"
biolith = "3.3.5"

sodium = "mc1.21.8-0.7.0-fabric"
modmenu = "15.0.0"

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }

[libraries]
minecraft = { group = "mojang", name = "minecraft", version.ref = "minecraft" }
parchment = { group = "org.parchmentmc.data", name = "parchment-1.21.8", version.ref = "parchment" }

fabric_loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric_loader" }
fabric_api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric_api" }

specter_block = { group = "dev.spiritstudios.specter", name = "block", version.ref = "specter" }
specter_config = { group = "dev.spiritstudios.specter", name = "config", version.ref = "specter" }
specter_core = { group = "dev.spiritstudios.specter", name = "core", version.ref = "specter" }
specter_serialization = { group = "dev.spiritstudios.specter", name = "serialization", version.ref = "specter" }
specter_gui = { group = "dev.spiritstudios.specter", name = "gui", version.ref = "specter" }
specter_entity = { group = "dev.spiritstudios.specter", name = "entity", version.ref = "specter" }
specter_item = { group = "dev.spiritstudios.specter", name = "item", version.ref = "specter" }
specter_registry = { group = "dev.spiritstudios.specter", name = "registry", version.ref = "specter" }
specter_render = { group = "dev.spiritstudios.specter", name = "render", version.ref = "specter" }
specter_worldgen = { group = "dev.spiritstudios.specter", name = "worldgen", version.ref = "specter" }
specter_debug = { group = "dev.spiritstudios.specter", name = "debug", version.ref = "specter" }

geckolib = { group = "software.bernie.geckolib", name = "geckolib-fabric-1.21.8", version.ref = "geckolib" }
biolith = { group = "com.terraformersmc", name = "biolith-fabric", version.ref = "biolith" }

sodium = { group = "maven.modrinth", name = "sodium", version.ref = "sodium" }
modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu" }

[bundles]
specter = [
	"specter_block",
	"specter_config",
	"specter_core",
	"specter_entity",
	"specter_item",
	"specter_registry",
	"specter_render",
	"specter_gui",
	"specter_serialization",
	"specter_worldgen"
]
